name: staffstuff
version: '${version}'
main: org._1104mc.staffstuff.Staffstuff
api-version: '1.20'
authors: [Peter Horvath]
description: A staff manager plugin
website: https://github.com/1104mc/staffstuff
commands:
  activate:
    description: Activate your manager roles!
  deactivate:
    description: Deactivate your manager roles!
  kick:
    description: Simple kick command! Minimal role is staff!
  timeout:
    description: Mute players on chat for a specified time. Staff role is the minimun to use this command.
    aliases:
      - tm